  spring:
    application:
      name: probate-spring-boot-template

  server:
    port: 8555

  management:
    endpoints:
      web:
        exposure:
          include: health,info
        base-path: /
    endpoint:
      health:
        show-details: always
        enabled: true

  authorised.services: probate_backend

  auth.provider.service.client:
    baseUrl: http://localhost:4502
    microservice: 'probate_backend'
    key: 'AAAAAAAAAAAAAAAA'
    tokenTimeToLiveInSeconds: '900'

  idam.s2s-auth.url: ${auth.provider.service.client.baseUrl}

  auth.idam.client.baseUrl: http://localhost:4501
