  spring:
    application:
      name: probate-spring-boot-template

  server:
    port: 8555

  auth.provider.service.client:
    baseUrl: http://localhost:4502
    microservice: 'probate_backend'
    key: 'AAAAAAAAAAAAAAAA'
    tokenTimeToLiveInSeconds: '900'

  idam.s2s-auth.url: ${auth.provider.service.client.baseUrl}
